apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Simple CloudBees Workflow Using Checkout Action
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - id: checkout
        name: Checkout repository
        uses: cloudbees-io/checkout@v1
        
      - id: list-current-dir-contents-new
        name: List repository contents
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "Repository contents:"
          ls -la
          echo ""
          echo "Current working directory:"
          pwd
