apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
deploy:
    uses: org/repo/reusable.yaml
    environment: QA
    secrets:
      asecret: ${{ secrets.secret1 }} 
    with:
      aninput: ${{ vars.avalue }}
      artifactName:     ${{ inputs.artifactName }}
      artifactVersion:  ${{ inputs.artifactVersion }}
      environment:      "QA"
