apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    steps:
      - id: checkout
        name: Get source code
        uses: cloudbees-io/checkout@v1

      - name: Show current directory
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          pwd

      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
